; PlatformIO configuration for BLE advertisement load generator
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[common]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 1500000
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.2
build_flags =
    -D CONFIG_BT_NIMBLE_TASK_STACK_SIZE=4096
    -D CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=4096

[env:esp32dev]
extends = common
board = esp32dev
build_flags =
    -D ARDUINO_ARCH_ESP32
    -D CONFIG_BT_NIMBLE_PINNED_TO_CORE=1
    ${common.build_flags}

[env:esp32c3]
extends = common
board = esp32-c3-devkitm-1
board_build.flash_mode = dio
build_flags =
    -D ARDUINO_ARCH_ESP32C3
    -D CONFIG_IDF_TARGET_ESP32C3
    -D CONFIG_BT_NIMBLE_PINNED_TO_CORE=0
    ${common.build_flags}

[env:esp32s3]
extends = common
board = esp32s3box
build_flags =
    -D ARDUINO_ARCH_ESP32S3
    -D CONFIG_IDF_TARGET_ESP32S3
    -D ARDUINO_USB_MODE=1
    -D CONFIG_BT_NIMBLE_PINNED_TO_CORE=1
    ${common.build_flags}
